name: test
on:
  push:
    branches:
      - new-design
  pull_request:

env:
  CI: "true"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
      - run: npm install
      - run: npm test

  #    - name: Install dependencies
  #      run: npm ci

      - name: Run build
        run: npm run build
