name: test
on:
  push:
    branches:
      - new-design
  pull_request:
      - new-design
env:
  CI: "true"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache .npm
        uses: actions/cache@v1
        env:
          cache-name: cache-dot-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          check-latest: true
      - run: npm install
      - run: npm test

#      - name: Install dependencies
#        run: npm ci

      - name: Run build
        run: npm run build
