name: test
on:
  push:
    branches:
      - new-design
  pull_request:

env:
  CI: "true"

jobs:
  test:
    name: Building environment...
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
        check-latest: true
    - run: npm ci
#    - name: Install dependencies
#    - run: npm ci
    - name: Run build...
      run: npm run build
